version: "3.9"
services:
  db:
    image: postgres
    ports:
      - '5432:5432'
    volumes:
    #  - ./tmp/db:/var/lib/postgresql/data
      - postgresql-data:/var/lib/postgresql/data

    environment:
      POSTGRES_PASSWORD: password
    tty: true
    stdin_open: true

  web:
    build: .
    #command: bash -c "rm -f tmp/pids/server.pid && bundle exec bin/rails s -p 3000 -b '0.0.0.0'"
    command: bash -c "rm -f tmp/pids/server.pid && ./bin/dev"
    tty: true
    stdin_open: true
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db
volumes:
  postgresql-data:
    driver: local